---
globs:
  - '**/*.md'
  - '!.venv*/**/*.md'
  - '!**/.tox/**/*.md'
  - '!**/.pytest_cache'
  - '!CHANGELOG.md'
  - '!generated/**'
  - '!openspec/**/*.md'
  - '!.opencode/**/*.md'
  - '!.agent/**/*.md'
  - '!.github/skills/**/*.md'
  - '!.github/prompts/**/*.md'
  - '!.gemini/skills/**/*.md'
